"""empty message

Revision ID: 5f78e893399d
Revises: 
Create Date: 2024-03-17 19:44:19.486359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f78e893399d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('numrooms', sa.String(length=80), nullable=True),
    sa.Column('numbathrooms', sa.String(length=80), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('property_type', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    # ### end Alembic commands ###
